### ISSUE TITLE
Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'System.String'.

### ISSUE THREAD

**Issue by robertjf** [KOBENDigital/Iconic#13]
There's an issue when using Iconic in a Nested Content (and possibly Stacked Content) template where the ValueConverter throws the following:

>Exception Details 
>System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'System.String'. 
>Stacktrace 
>at Koben.Iconic.ValueConverters.IconicValueConverter.ConvertSourceToObject(PublishedPropertyType propertyType, Object source, Boolean preview)
>   at Umbraco.Web.Models.DetachedPublishedProperty.<.ctor>b__7_1()
>   at System.Lazy`1.CreateValue()
>   at System.Lazy`1.LazyInitValue()
>   at System.Lazy`1.get_Value()
>   at Umbraco.Web.Models.DetachedPublishedProperty.get_Value()
>   at Umbraco.Web.PublishedPropertyExtension.GetValue[T](IPublishedProperty property, Boolean withDefaultValue, T defaultValue)
>   ...

**Comment by robertjf** [comment]
@skartknet just sent a PR to fix this issue for you
